development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: rentadriveway_dev
  pool: 5
  username: mysql_root 
  password: mysql_root 
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: rentadriveway_test
  pool: 5
  username: mysql_root
  password: mysql_root

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: rentadriveway_prod
  pool: 5
  username: mysql_root
  password: mysql_root
